### ISSUE TITLE
Parse error au lancement de devtool

### ISSUE THREAD

**Issue by loca-a** [Anakeen/development-tools#31]
PHP Parse error:  syntax error, unexpected '<<' (T_SL), expecting ',' or ';' in phar:///root/dev/development-tools-3.2/dynacase-devtool.phar/src/Dcp/DevTools/Utils/ConfigFile.php on line 9

Il est interdit de déclarer un const avec une expression le code ne peut donc pas être utilisé en l'état.

OS : centos 7
php : 5.4.16

De plus, contrairement à ce qui est écrit dans la notice, la compilation n'est pas possible car le fichier box.phar n'est pas présent dans le package disponible (vu dans aucun des répertoires de l'archive)

**Comment by Eric-Brison** [comment]
Le support des expressions de constante a été ajouté en PHP 5.6.0. 
Les versions de PHP supportées par Dynacase sont PHP 5.6 et PHP 7.0

**Comment by cbonnissent** [comment]
De plus, le fichier box est accessible via le lien déposé dans le README principal

**Comment by cbonnissent** [comment]
Not an issue
