### ISSUE TITLE
createModule ne donne pas l'arborescence complète

### ISSUE THREAD

**Issue by loca-a** [Anakeen/development-tools#33]
PHP 5.6
La commande " php dynacase-devtool.phar createModule -o ./COGIP -n cogip_audit _a COGIP_AUDIT -xspi -e" créé une partie seulement de l'arborescence contrairement à ce qui est détaillé dans le quick start (http://docs.anakeen.com/dynacase/3.2/dynacase-quickstart/dynacase-quickstart:5b0e5ec5-1f8d-49ea-9953-42727cdc1b2b.html#dynacase-quickstart:5b0e5ec5-1f8d-49ea-9953-42727cdc1b2b)

Seuls les fichiers build.json, info.xml et le répertoire locale sont créés.

**Comment by cbonnissent** [comment]
Bonjour,

Désolé du temps de réponse un peu long, je n'avais pas vu l'issue mais je me suis inscrit pour les suivre.

La commande est invalide => l'options de l'application -a est notée en _a 

En utilisant la commande suivante 

`
$ ./buildtools/dynacase-devtool.phar  createModule -o /tmp/test/ -n cogip_audit -a COGIP_AUDIT -xspi -e
.. terminé.
.. terminé.
.. terminé.
.. terminé.
$ ls -al /tmp/test/
total 12
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 .
drwxrwxrwt 2 root    root      0 sept. 15 09:33 ..
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 API
-rw-rw-rw- 1 charles charles 391 sept. 15 09:33 build.json
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 COGIP_AUDIT
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 EXTERNALS
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 Images
-rw-rw-rw- 1 charles charles 732 sept. 15 09:33 info.xml
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 locale
drwxrwxrwx 2 charles charles   0 sept. 15 09:33 STYLE`

=> Pour info, la commande indiquée dans le [quickstart](https://docs.anakeen.com/dynacase/3.2/dynacase-quickstart/dynacase-quickstart:5b0e5ec5-1f8d-49ea-9953-42727cdc1b2b.html#dynacase-quickstart:6207b157-95a4-4a53-b112-fbb5c2b58741) est valide.
